### ISSUE TITLE
Virtual Orders Planning

### ISSUE THREAD

**Issue by e00E** [gnosis/dex-services#1126]
Based on https://docs.google.com/document/d/1oLdbeJZQmTJtrFVOj5hmtWWIkjC8pgB579PQm3KStCE/ .

Design the API:
- [ ] What is the authentication scheme (api key vs proof of address)?
- [ ] Design and document the http api that supports the operations: post virtual order, get virtual orders, get historic virtual orders.
- [ ] Document rules and guidelines for market makers for using the api. 

Design the backend:
- [ ] How do we persist virtual orders? This has to allow us to query historic virtual orders and be upgradable in case we add new fields to virtual orders in the future.
- [ ] In what language and framework do we implement the backend?

Implement the backend:
- [ ] Implement the documented api.
- [ ] Set up kubernetes for the persistent database (if we have one) and the backend.
- [ ] Update the price estimator to make use of the backend.

Integrate marked makers:
- [ ] Implement tools to verify that market makers comply with their virtual orders.
- [ ] Find interested market makers and communicate api documentation and api keys to them and add them to the whitelist.

**Comment by nlordell** [comment]
>  What is the authentication scheme (api key vs proof of address)?

API Key for now I think.

**Comment by fleupold** [comment]
> API Key for now I think.

Do we have the arguments around that decision collected somewhere? One advantage of using proof of address is that ultimately sending the on-chain tx requires your signature anyways so all of the logic for signing payloads with your PK should already be available to the developer. It would also "bond" people to pay extra attention to that key as it's likely related with at least some gas money.

On the flipside, a direct mapping of `key -> order` owner might not be realistic since the order could be owned by some wrapper or pooling contract and not actually by the EOA sending the transaction.

**Comment by e00E** [comment]
> all of the logic for signing payloads with your PK should already be available to the developer

This doesn't have to be true. Depending on the ethereum library used it might not be easy to sign arbitrary bytes.

Api key is simpler to implement. And the argument that there might be multiple addresses associated with a market maker and they might not know in advance from which address they'll place the order makes sense to me.

**Comment by fleupold** [comment]
> Depending on the ethereum library used it might not be easy to sign arbitrary bytes.

Do you have an example? Given that signing is part of the RPC standard (https://eth.wiki/json-rpc/API#eth_sign) I would expect every reasonable web3 library to implement it.

> Api key is simpler to implement.

The only thing I can think about is that signatures requires an additional [ecrecover](https://tomusdrw.github.io/rust-web3/web3/signing/fn.recover.html) to extract the public key from the payload . Otherwise managing a list of public keys or API keys, should be the same. Is there some other aspect that is simpler about API keys?

Even in the case of API Keys, I would think we need some form of mapping from key to address list so that we can verify if orders were placed accordingly.

**Comment by e00E** [comment]
I don't have a specific example, just my intuition. What you link is the api of the ethereum node but I could see that the application placing the virtual orders itself might not want to have to go through an external node to sign something or might not have access to a private key.
I don't like using this word usually but "obviously" it is simpler to append the hardcoded string api key to an http request than going through an ethereum node or library to sign a message. Then we also need to think about what exactly the message being signed is since that works on bytes but we only have an abstract http request or abstract virtual order type.

> Even in the case of API Keys, I would think we need some form of mapping from key to address list so that we can verify if orders were placed accordingly.

Yes, in both cases we will need to keep an association of address to market maker.

**Comment by fleupold** [comment]
I see. My original understanding was that it would be simpler on our end to use API keys, but I think what you are saying now is that it will be simpler for the market maker that is integrating.

> I could see that the application placing the virtual orders itself might not want to have to go through an external node to sign something or might not have access to a private key.

Something under the control of the MM needs to have access to the PK and talk to the node to place the order in the end. And since the original logic for "how much am I willing to pay" and "am I willing to pay less than current on-chain book asks" seem very related I would be surprised if they don't happen in the same code.

But you are right that the API key is more flexible in this regard (it's just another thing that the client needs to configure and store in a safe way). 
Needless to say that API Keys need to be sent over encrypted channels (signatures could be transmitted in plain text) but forcing HTTPS seems like a trivial thing to add.

**Comment by nlordell** [comment]
> Do we have the arguments around that decision collected somewhere?

No, just my opinion. Its based on the fact that a API key can be implemented as a simple table with `API_KEY` and `MM ID` columns, or `HashMap<ApiKey, MarketMakerId>` in memory.

> One advantage of using proof of address is that ultimately sending the on-chain tx requires your signature anyways so all of the logic for signing payloads with your PK should already be available to the developer. It would also "bond" people to pay extra attention to that key as it's likely related with at least some gas money.

I think we don't want MM to require placing orders with a single address that is registered with the price estimator - it may not work well with their workflows. To me the biggest advantage of using proof of address (PoA) is that it more easily facilitates managing trusted MM on-chain. This would be useful if say, the dxDAO wanted to manage trusted MM on-chain. The MM would then send some signed data, we could recover the address from the signature and check the dxDAO trusted MM contract to see if that address is indeed a trusted MM (just spitballing).

> Depending on the ethereum library used it might not be easy to sign arbitrary bytes.

I think if we are providing integration libraries, its reasonable for us to provide this to MMs as part of some integration SDK. I don't think this is very much a concern. Also, in general:
```
$ curl -H "x-api-key: $API_KEY" https://dex-virtual-orderbook/...
```
to me is just as easy as:
```
$ curl -H "x-api-key: $(sign message)" https://dex-virtual-orderbook/...
```

> The only thing I can think about is that signatures requires an additional ecrecover to extract the public key from the payload.

To me one complicated question which would require more thought than a simple API key is "what should be signed?". This would be my main argument as to why API keys are simpler to implement.

**Comment by nlordell** [comment]
Maybe we can close this issue for now until we revisit the virtual orderbook?
