### ISSUE TITLE
Temporarily make nonce and cancellation errors benign

### ISSUE THREAD

**Issue by nlordell** [gnosis/dex-services#1192]
In order to have the alerts channel be less noisy, we should make the nonce errors and some other congestion related errors temporarily benign:
1. `failed to cancel solution submission of batch X after deadline: ExecutedOrder(ConfirmTimeout)`
2. `Transaction gas price supplied is too low. There is another transaction with same nonce in the queue. Try increasing the gas price or incrementing the nonce.`
3. `Transaction nonce is too low. Try incrementing the nonce.`

We can also potnetially make the following benign:
4. `Batch X failed with unretryable error: solution submission transaction not confirmed in time`
5. `There are too many transactions in the queue. Your transaction was dropped due to limit. Try increasing the fee.`

**Comment by e00E** [comment]
#1193 is going to fix 1, 2, some instances of 3, 5. 
3 can still occur in the instances that are fixed by "fix race condition" PRs. We can make those benign temporarily and revert it in those PRs.
4 I am not sure whether it should be benign or not. We create this error when we had to cancel the solution submission transaction. This can be benign if the gas prices rose quickly but it could also indicate retry_with_gas_price not having worked correctly.

**Comment by nlordell** [comment]
> . 4 is hopefully rare enough that we don't need to handle this case.

It was fairly common last week unfortunately :cry:  I think it would be nice to temporarily make this benign until #1187 is implemented.

**Comment by e00E** [comment]
It shouldn't be common with the change that the gas price has to be at least *fast*. I believe all the instances we have seen it were because of very low gas max gas price.
