### ISSUE TITLE
Solution submission out of gas

### ISSUE THREAD

**Issue by e00E** [gnosis/dex-services#1243]
https://etherscan.io/tx/0x0030d16830e8b68c138eefdac40f95f7e3124494cff47ba1d076eefa46d6c740

This transaction at 2020-08-03T15:43:18.113Z from dev-dfusion-best-ring-solver-mainnet-master for batch 5321563 failed because it ran out of gas.

Should we change the gas limit? I'm guessing that this happened because it had to revert a 30 trades solution and also submit a new 30 trades solution.

**Comment by fleupold** [comment]
According to our worst case smart contract test we should be using 6M instead of 5.5M gas (https://github.com/gnosis/dex-contracts/blob/master/test/LargeExamples.spec.ts#L16)

I reran the same tx in tenderly with 6M gas and it passed:

<img width="1240" alt="Screen Shot 2020-08-04 at 12 26 58" src="https://user-images.githubusercontent.com/1200333/89283686-d9048780-d64d-11ea-8836-0695c0a050cb.png">

Interestingly, it ends up using less than 5M gas. This is because refunds (for releasing storage) only get applied at the end of the tx. However the remaining gas needs to be >0 at every point throughout the tx:

<img width="1397" alt="Screen Shot 2020-08-04 at 12 28 37" src="https://user-images.githubusercontent.com/1200333/89283793-110bca80-d64e-11ea-839a-ca8a880d5c49.png">
