### ISSUE TITLE
[PoC] Setup solver and driver in Rinkeby

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-services#274]
Setup with devops the full setup running on the servers so when users submit orders to the smart contract, they are **matched using the solver** and the **solutions for every batch are sent automatically**.

The solver can use any optimization criteria that gives feasible solutions. So it doesn't need to have the latest researches in the goal function. **Trading volume would suffice**.

It should be easy to deploy new versions, ideally **automatically using the CI** as long as the test passes.

Good to have, would be to have **two completely separate environments `develop` and `staging`**, both pointing to `Rinkeby`. This way, we can have staging as the stable version with the current setup that maximizes trading volume, and then we can work freely always in new features, contracts, solvers in develop without affecting the staging version. The web and bots use already this approach, so it would be ideal to have different environments.

**Comment by anxolin** [comment]
@fleupold, @denisgranha, what do you think about this issue?

**Comment by fleupold** [comment]
We don't have a develop branch and don't really need one, but if you prefer having a "stable" version, I'd suggest we use github tags for that - could probably be deployed as a stable image so that we only need one AWS pod running the latest tag.

What do you think?

**Comment by denisgranha** [comment]
stable using tags rather than a branch means we have to change the configuration manually. I think would be preferable to have a branch for stable/staging and then use the tag approach for production (that’s what we do in the other projects)

My concern is avoiding manual processes in develop/staging environments

**Comment by bh2smith** [comment]
I assume this issue has been created in accordance with the recent sprint planning and reflects the following text:

```
Deploy Rinkeby driver/solver on AWS
When placing an order from a local machine, there will be a driver running remotely who submits auction solutions.
```

if this is not the case, please let me know and I will create another issue.

**Comment by fleupold** [comment]
> I assume this issue has been created in accordance with the recent sprint planning

Exactly

@denisgranha the thing is that we do not have a staging branch (and don't think that we want or need one), so I'm not sure what the best approach would be.

We could take a snapshot of master every week at a certain time and make this our staging, but since we don't have any users I'm not sure when we would call a master commit ready for staging. Maybe we should just work off master until we are actually launched?
