### ISSUE TITLE
Remove Fixed Default Gas And Gas Price

### ISSUE THREAD

**Issue by nlordell** [gnosis/dex-services#369]
Instead use `estimate_gas` and `estimate_gas_price` (or gas station) to get the values to use. `ethcontract` will automatically estimate the gas amount when sending transactions.

**Comment by fleupold** [comment]
Does eth_contract allow specifying a target time (e.g. slow, avarage, fast)? For the solver, we'd want to make sure we are using a fairly high gas price (but you are right that we should not hard code 20GWEI).

I'd suggest something like 20% (or some other constant) more than the fast price reported by https://ethgasstation.info/

**Comment by fleupold** [comment]
As a next step, we should be using the gnosis safe gas station which is documented here: https://gnosis-safe.readthedocs.io/en/latest/services/relay.html#api-v1-gas-station-get

**Comment by e00E** [comment]
Is there a next step or is this issue done?

**Comment by fleupold** [comment]
I think the issue is done, although it would be nice to measure the impact of this (e.g. when we settle an auction compare the gas price we paid with however much we would have paid without it)?

Maybe this could be done at tomorrow's trading challenge where we expect to see a bunch of settlements. We could query the estimate_gas_price of our full node as we submit the solutions and compare the difference empirically.
