### ISSUE TITLE
Add Prometheus Metrics

### ISSUE THREAD

**Issue by fleupold** [gnosis/dex-services#419]
In order to get better alerting and metrics, we should use proper metrics logging (e.g. prometheus) directly in the dex-services.

Some metrics we could be logging
- number of successful/failed price_finding cycles
- objective value reported
- number of orders in a batch
- number of different tokens in a batch
- number of touched orders in a solution
- prices set per auction
- time between beginning of run loop to submitting the solution (and how far into the 4 minute solution finding period that is)

[This package](https://github.com/tikv/rust-prometheus) looks like a good rust implementation of a prometheus client.

@luarx has apparently experience with Prometheus on the dev ops side and could be our point of contact.

**Comment by fleupold** [comment]
My suggestion would be to implement a StableXMetrics trait with the following interface:

- auction_processing_started(Result<batch, error>)
- auction_orders_fetched(Result<orders, error>)
- auction_solution_computed(Result<solution, error>)
- auction_solution_verified(Result<objective_value, error>)
- auction_solution_submitted(Result<tx_hash, error>)
- auction_skipped(reason) // e.g. trivial vs. too_late

Implementations of that trait would be responsible for doing all logging (e.g. to console and into prometheus metrics).

This would allow us to gather the metrics mentioned above. In particular it would allow us to measure the exact time passed between all sub-steps, which can be used for performance optimization of the flow.

Regarding the [types of the metrics](https://prometheus.io/docs/concepts/metric_types/#gauge):
- Number of cycles should probably be a counter
- Information about the batches (number of orders/tokens) could be a gauge as they shouldn't change dramatically between auctions
- Information about the solution (number of touched orders/number of prices/objective value) could be a histogram as it's likely to be very different from auction to auction
- timings should probably be histograms

@e00E what do you think?

**Comment by e00E** [comment]
> My suggestion would be to implement a StableXMetrics trait with the following interface:

It is hard to visualize how this would work out in the code, its something we have to try out. A source of error could be that the functions have to be called in the correct order and that data from the previous call is needed: to calculate how long `solution_verified` took you need to have remembered the timestamp of `solution_computed`. It might not be a problem in practice.

Keep in mind that Prometheus is not logging, its metrics that are usually `counter`s that are accumulated. For example, in a webserver with Prometheus you cannot retrieve the handling time per individual request.
You can keep track of the total number of requests and total handling which Prometheus would samples every 10 seconds. Then you can plot the moving average handling time and check if handling times change over time. If you wanted more detail you would use a histogram to accumulate the handling time in buckets like 1ms, 10ms, 100ms.

A `gauge` is something like the memory usage of the server that goes up and down over time. Prometheus samples the gauge in a fixed interval. In the webserver example you could say that you are going to use a gauge to represent the number of handled requests per second but that would not be natural. It is better to use the total number of requests and calculate the per second value later (because Prometheus remembers the total at each sampling point).

With that in mind, anything per auction/cycle (are they the same thing?) should be a counter or a histogram (which is just several counters each representing a bucket).

A gauge could be the memory usage of the program as reported by the operating system or the total number of unprocessed (still waiting) orders.

**Comment by fleupold** [comment]
> Keep in mind that Prometheus is not logging, its metrics that are usually counters that are accumulated

The implementation of StableXMetrics would both log to stdout as well as to Prometheus.

As for the gauge, I do think that orders in the current auction is something comparable to memory usage that goes up and down over time. It's kind of the "pressure" for the python solver. 
While it would be possible to have a "total orders processed" counter and derive the value of each batch by subtracting the last two data points, the same would theoretically be true for memory consumption (you can just accumulate total RAM used ever).
I guess if we used a histogram this would actually give us more granularity (how many auctions with <10, <100, <1000 orders)

I think system metrics (such as memory usage & CPU) are already tracked by infrastructure wide prometheus logging and don't need to be application specific.

**Comment by e00E** [comment]
> the same would theoretically be true for memory consumption (you can just accumulate total RAM used ever)

You could accumulate total allocated and freed memory which would be an improvement over having just the gauge if you have access to those values. It would allow you to notice if the application was allocating 1GB of memory per second but also freeing the same amount, which is exceptional but something a raw Gauge cannot show.

> derive the value of each batch by subtracting the last two data points

Afaik this is not in the spirit of prometheus. You should not have to know the sampling interval to get meaningful stats. Assume that the prometheus server queries the application for the current metrics at random times and that querying the metrics is a side effect free function in the application.

In this case I am not sure whether *orders in the current auction* or *total orders processed* is better. If the duration of an auction is significantly longer than the sampling interval then it can be useful. We can start with both metrics and see which one works better in practice.
