### ISSUE TITLE
Which http client library should we use

### ISSUE THREAD

**Issue by e00E** [gnosis/dex-services#535]
In #530 and #533 we need to make http requests. It makes sense to use the same http client library everywhere in the code. Which one should we pick?

1. https://crates.io/crates/isahc
2. https://crates.io/crates/reqwest
3. https://crates.io/crates/hyper
4. https://crates.io/crates/curl
5. https://crates.io/crates/surf
6. ?

Both support blocking requests and async/await.
reqwest depends on Tokio while isahc doesn't.
isahc uses libcurl internally while reqwest is pure rust.
reqwest is the most popular http client.

A month ago someone tested rust http clients https://medium.com/@shnatsel/smoke-testing-rust-http-clients-b8f2ee5db4e6 .

@nlordell @fleupold @bh2smith 

**edit(@nlordell)**: Added a few more options.

**Comment by bh2smith** [comment]
I originally would have thought that reqwest would be the natural choice given it popularity, but have also heard that people tend to try and avoid this tokio dependency. However, I believe we already depend on tokio anyway and that it is unlikely this will change anytime soon. As a second option, I would lean towards curl mostly because it is something I am already well aware of and I’m an “old dog”.

**Comment by e00E** [comment]
Without having tried it, I don't think that the isahc crate is similar to curl. It just uses it internally as the backend.

If we ever want to make use of async in the future we will most likely depend on Tokio anyway.

**Comment by nlordell** [comment]
> If we ever want to make use of async in the future we will most likely depend on Tokio anyway.

:cry:

**Comment by e00E** [comment]
Maybe I am wrong about probably needing tokio. That was just my impression. I don't have a strong opinion on which library anyway, so I am happy to use isahc if you prefer it.

**Comment by bh2smith** [comment]
> so I am happy to use isahc if you prefer it.

Both of us said we prefer `curl`.

**Comment by vorot93** [comment]
I think that the tendency of some to avoid Tokio is probably a leftover from the older days of async where *everything* had piss poor API: Tokio, futures-rs, most of other foundational crates. Today Tokio runtime is very fast, polished and configurable.

request is a premier http client with production usage like no other. By contrast, I had poor experience with surf+isahc combo where each new instance of client spawned an additional thread (!).

Disclaimer: I may be a bit biased because I'm a member of Tokio project myself.

**Comment by nlordell** [comment]
Yes, `isahc` spawns a thread per client for async requests in order to drive the future. However if you use a single `HttpClient` instance there will only be one extra thread.

To be clear I think `tokio` Is a super awesome project that allows really high performance concurrency, but it definitely does add complexity because it needs a runtime that needs to be setup and is checked at runtime and not by the compiler. And this is my main gripe.

For performance, `tokio` is definitely better because of its runtime, but things like `async-std` and `isahc` “just work” at the cost of foregoing some optimizations that are made possible by sharing a runtime.

Since services doesn’t really need to scale in this way, personally I prefer sacrificing a small amount of performance, especially considering it doesn’t matter in this context, for things to just work and avoid hard to debug runtime issues.

**Comment by vorot93** [comment]
`Tokio`'s runtime also "just works" as you can slap a `#[tokio::main]` main macro on top of your main and be done with it. The problems you mentioned most likely come from the 0.1 -> 0.2 transition - this is the same old multiple version in the dependency graph problem that you can encounter with any other dependency. It is simply not fair put special blame on Tokio here.

**Comment by fleupold** [comment]
I'm by no means an expert on low level networking libraries and impressed by the detailed discussion (beyond my level of knowledge).

As mentioned by others already, I don't think peak performance is our main concern, as we are likely going to do less than simple GET 10 requests per minute. 

I'd be in favour of using the most lightweight and easy to reason about system, that is quick to integrate into the codebase and develop with. Right now everything in the services is running in a recurring synchronous runloop so we are not exposed to any tokio runtime.
We could also consider increase in build times for each library (although given that we transitively depend on tokio anyways it's likely not a big difference).

In any case it might be worthwhile hiding the specific choice behind a dex-services specific HTTPRequester shim which would make it easy to replace the underlying library later if we decided to.

**Comment by vorot93** [comment]
2 things to note here:
* If there's no need for async, [reqwest has a blocking client implementation](https://docs.rs/reqwest/0.10.1/reqwest/blocking/index.html).
* `tokio` crate is highly customizable and allows switching off work-stealing runtime altogether for single-threaded applications. [This results in faster builds and slimmer binaries](https://github.com/tokio-rs/tokio/issues/1791#issuecomment-557202625). `async-std` is monolithic in this respect.

**Comment by nlordell** [comment]
> Tokio's runtime also "just works" as you can slap a #[tokio::main] macro on top of your main and be done with it.

Only as long as only a single version of the runtime is needed. The thing is the requirement of this runtime is *implicit* in that it is not verified by the compiler.

Other libraries that depend on `async-std`, for example, “just work” because it is not the callers responsibility to drive futures, but something that is handled internally by the framework, which usually spawns a thread for you which does similar work to what the `tokio` runtime does (sometimes very inefficiently like you pointed out with one thread being created per request in `surf` with `isahc`, which is suboptimal to say the least).

The big difference is when you have dependencies that use different versions of `async-std`, from what I understand, they will each spawn their own threads that drive IO, so dealing with different versions is not as painful.

**Comment by vorot93** [comment]
Actually, what `async-std` does is it provides a global variable, a single `God` runtime which referenced by all libraries using it and is neither switchable nor customizable. With Tokio you build and set your own runtime, even if by simply using `#[tokio::main]`.

Having `runtime versions` * `cpu cores` threads is, well, workable but very questionable from an engineering point. Even if such an approach is preferable, [tokio provides tokio-compat for running crates that depend on legacy versions](https://github.com/tokio-rs/tokio-compat).

**Comment by nlordell** [comment]
That is the point I’m trying to get at, in that `async-std` ensures this runtime is running for you, even if it is in a suboptimal way where one is created per version of `async-std` linked into the binary.

This is both a con (for obvious reasons) but also a pro in that this extra responsibility is removed from the developer.

**Comment by vorot93** [comment]
I think using `tokio_compat::run_std(async move { ... })` accomplishes legacy runtime coverage just as well.

**Comment by nlordell** [comment]
Yes, that works but there is nothing preventing me from doing `futures::executor::block_on(some_tokio_future)` and failing miserably.

**Comment by vorot93** [comment]
There is nothing preventing from calling `unreachable!()` either. I mean, you shouldn't be using the dummy executor from futures-rs in the first place.

**Comment by nlordell** [comment]
> There is nothing preventing from calling `unreachable!()` either. I mean, you shouldn't be using the dummy executor from futures-rs in the first place.

I don't think this is a valid analogy as the expectation when calling `unreachable!()` is that the application will panic while the expectation when calling `futures::executor::block_on` is that my future will be polled to completion.

> Rust in general provides plenty of opportunities for willingly shooting yourself in the foot

I'm not sure I agree with this. I think Rust's type system goes above and beyond to try to get you to not shoot yourself in the foot. In fact I think guaranteeing memory and thread-safety are at the core of Rust's design goals.

> Tokio provides handrails for migration between versions

I agree, `tokio` provides solutions to all the things mentioned above. Like I said, `tokio` is awesome! It provides a ultra-performant concurrency that can be controlled to work exactly to suit the needs of an application. I actually really enjoy reading the `tokio` blogs as they are very interesting and insightful. Like I said, my only complaint is that the presence of the runtime is not verified by the compiler, when I would hope that it would be. This can lead to sneaky and hard to debug issues, especially for people who are not familiar with the async landscape.

> but actually running the foreign runtime with Tokio's primitives is just straight-up brain-dead.

I'm not sure I understand what you mean.

**Comment by nlordell** [comment]
Also it is worth mentioning that `isahc` does not depend on `async-std`. It drives its futures by spawning a thread and using `libcurl` "multi" API and should be pretty slim, and possibly slimmer than `reqwest`.

**Comment by nlordell** [comment]
> I mean, you shouldn't be using the dummy executor from futures-rs in the first place.

I didn't know there were any serious issues with the `futures-rs` executor. Looking at the implementation its a single thread that polls a future then parks the thread waiting for the waker to be called so the thread can continue. If you have a single top-level future, this should be fine right? Or am I missing something?

**Comment by vorot93** [comment]
`LocalPool` passes away the waker with unpark to the future and parks the main thread so that _someone else_ can wake it. An almost dummy executor.

`ThreadPool` is pure busy loop.

**Comment by nlordell** [comment]
Alright, so I compiled a table with some of the things we talked about:

| **crate**  | **dependencies** | **build time** + | **binary size** + | **runtime** | **async** | **language** |
|------------|-----------------:|-----------------:|------------------:|:-----------:|:---------:|:------------:|
| reqwest ++ |              117 |  23.75s / 47.13s |      39MB / 6.0MB |   yes +++   |    yes    |     Rust     |
| curl       |               19 |    3.53s / 7.44s |     3.9MB / 2.6MB |      no     |  no ++++  |    C/Rust    |
| isahc      |               44 |  13.87s / 24.33s |      15MB / 3.7MB |      no     |    yes    |    C/Rust    |

> - +: values are for debug / release builds
> - ++: `reqwest` with the `blocking` feature enabled
> - +++: setting up a runtime is not needed for the blocking API
> - ++++: multiple simultaneous requests can be performed on a single thread with the "multi" API

Here are examples of doing a get and just printing the content to STDOUT:

### `reqwest`

```
fn main() {
    let body = reqwest::blocking::get("https://www.rust-lang.org")
        .unwrap()
        .text()
        .unwrap();
    println!("{}", body);
}
```

### `curl`

```
use curl::easy::Easy;
use std::io::{self, Write};

fn main() {
    let mut request = Easy::new();
    request.url("https://www.rust-lang.org/").unwrap();
    request
        .write_function(|data| {
            io::stdout().write_all(data).unwrap();
            Ok(data.len())
        })
        .unwrap();
    request.perform().unwrap();
}
```

### `isahc`

```
use isahc::prelude::*;

fn main() {
    let body = isahc::get("https://www.rust-lang.org")
        .unwrap()
        .text()
        .unwrap();
    println!("{}", body);
}
```

**Comment by e00E** [comment]
I agree that the choice is between isahc and reqwest. I personally do not have a strong opinion between them and I cannot yet judge the async internals you have been debating. If no one else in dfusion has a strong opinion on the matter then we can go with isahc.

**Comment by fleupold** [comment]
This is a great summary @nlordell. I agree that it's a close call between isahc and reqwest and we would probably do fine with either. Because of that, I think it's ultimately up to your preference. 

I personally also prefer `isahc` as it seems more lightweight. We can also revisit if request and multithreading performance becomes a bottleneck.

**Comment by vorot93** [comment]
I don’t know if isahc can actually be considered lightweight since it’s merely a wrapper which brings in a foreign C library dependency. And lest we forget that C library means undetermined number of future CVEs to be aware of.

**Comment by fleupold** [comment]
> And lest we forget that C library means undetermined number of future CVEs to be aware of.

I'm not too worried about the security risk of using curl. It's not like the services are a prime target for attack (they don't store funds other than for paying gas). The only real attack vector is denial of service, and since curl is part of [Google's open source fuzzing effort](https://github.com/google/oss-fuzz/tree/master/projects/curl) I'm not to worried about random crashes.

**Comment by nlordell** [comment]
Closing this as we seemed to have settled on `isahc`. If performance ever becomes an issue, we will revisit `reqwest` in the future.
