### ISSUE TITLE
request is not supported because your node is running with state pruning

### ISSUE THREAD

**Issue by e00E** [gnosis/dex-services#544]
We get this message from time to time

> [driver] StableXDriver error: Driver Error: [method 'getEncodedUsersPaginated(address,uint16,uint16)' failure: web3 error: RPC error: Error { code: ServerError(-32000), message: "This request is not supported because your node is running with state pruning. Run with --pruning=archive.", data: None }]

This is probably related to us setting a fixed block number for the paginated order reading.  Maybe this only pops up now because the node is overloaded (getting gateway timeouts).

**Comment by fleupold** [comment]
@denisgranha how hard would it be to provide an archive node for dƒusion so that we can query past blocks (realistically it would only be a few blocks in the past at most)

The challenge is that we are doing paginated queries and would like to get a consistent view of the state balances. If those queries happen in different blocks, there is a chance for inconsistency (balance might have changed).

However, considering that we are likely querying the balances in the same 5 minute batch anyways (for which the results are consistent) we could potentially not specify a past block (in particular as the services should ideally in the long run work with standard infura nodes as well)

**Comment by denisgranha** [comment]
let me discuss it with the team and get back to you

**Comment by nlordell** [comment]
Re-opening this issue as it affects our orderbook reading.

**Comment by fleupold** [comment]
As mentioned on the PR, this should not be an issue. The reason it was an issue earlier was that we were behind a loadbalancer and would occasionally query blocks that the slower node had not yet synced with thus causing a "block does not exist" error.
