### ISSUE TITLE
[Listener] State Transition: Auction Settlement

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-services#56]
Function `applyAuction` should should emit an event containing, 

- `priceVector`
- `volumeVector` (aligning with the fractional fulfilment of each order placed in previous batch)
- `stateIndex`
- `stateRootHash`

Furthermore, this transition should also cause an update in the `balances` table.

**Comment by fleupold** [comment]
Turns out this is required before we can even fully test the driver support for order processing. The reason being:

We don't transition from state n to n+1 if an AuctionSettlement event is emitted at the moment. However, when we run the setupEnvironment we generate >20 blocks and therefore the first batch of deposits/withdraws/orders gets closed. The driver then does the following:
1) Run deposit driver (creates state_index 1 and emit StateTransition)
2) Run withdraw driver (creates state_index 2 and emit StateTransition)
3) Run auction driver (creates state_index 3 and emit AuctionSettlement)

Since 3) doesn't do anything to the database (the listener doesn't react to AuctionSettlement), the next time we want to e.g. process a deposit batch, the listener tries querying the balances from state_index 3 (the most recent state). However this one doesn't exist in the db and we crash.
