### ISSUE TITLE
New price feed (https://dex.ag/)

### ISSUE THREAD

**Issue by josojo** [gnosis/dex-services#585]
In order to improve the liability and the number of prices, which we can get for our tokens, we should implement one more price feed from https://dex.ag/

**Comment by e00E** [comment]
+ maybe price estimation outside of critical path

**Comment by nlordell** [comment]
Here is the API docs: https://docs.dex.ag/#api

**Comment by e00E** [comment]
For kraken we get the USD price for each token and use this as the OWL price. But dexag tracks neither USD nor OWL. So how should we calculate the price of a token in Owl?
It does track several stable coins (USDC, SUSD, USDT, TUSD) so one approach is to average them together to get an approximate USD price. Imo this would end up being too many requests per token.
Should we pick one specific stable coin?
Are there other solutions?

**Comment by josojo** [comment]
Currently, in our ecosystem, the DAI has the highest liquidity against most of the coins traded on our exchange. Hence, I would query all prices against DAI and then report these prices.

The small fluctuations DAI vs USD on various exchanges should be negligible for our solver.

**Comment by fleupold** [comment]
How does @marcovc deal with that at the moment in the dex-solver?

**Comment by marcovc** [comment]
Honestly what I've done is too basic for a definitive solution to this problem. The main problem I was trying to solve was to get at least one price estimate for all tokens, and not really went into these considerations. I ended up organizing tokens in groups of tokens: I assumed that any two tokens in one of these groups can act as a proxy for each other and thus have an equivalent price.  OWL endes up in the same group as USD and other stable coins pegged to USD, if I recall correctly. Likely this could be improved by taking the mean of the group as @e00E sugest, but again, what was on my mind of mostly what to do when these aggregators don't work for a particular token. Currently this is no longer a big issue since @twalth3r adapted the price estimation to work in a hybrid way where some of the tokens have external price and others don't.
