### ISSUE TITLE
Submit Solution: Retry with increased gas price

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-services#677]
The likely cause of the following failed transaction is that the gas price was not high enough to get this transaction processed in time.

https://etherscan.io/tx/0xc87c495f1d05203d4d1a48ba785a883e506c4cadd64ea8d88e9e70b4175f53e1

A reasonable fix here is to observe that the transaction is taking too long and increase the gas price to avoid the dreadful error "Solutions are no longer accepted for this batch".

An incremental solution proposed by @fleupold is to double the gas prices up to a maximum bound.

**Comment by fleupold** [comment]
Regardless of this we briefly discussed with @koeppelmann to cap the max gas price we are willing to pay at 100 GWEI

**Comment by bh2smith** [comment]
Assuming we get average gas estimates around 18 GWEI, then we would not be able to double for long.

```
18, 36, 72.
```

Perhaps we should consider 1.5x

**Comment by fleupold** [comment]
I think we will only have a very limited number of increase opportunities (there are only so many blocks in the remaining minute we are reserving for submission). 

If we are able to compute the solution much earlier, I'd rather start with the normal/low gas price instead of using `safe_fast` as we are doing at the moment. This way we should be able to save cost on average.
