### ISSUE TITLE
[e2e-test] Withdraw test has no setup

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-services#73]
_Question at bottom_

According to this script, one can withdraw without having run the initial setup (i.e. this test suggests that withdraws can be successful without an initial deposit). 

https://github.com/gnosis/dex-services/blob/b43e7dae6c48e4f3c9df115ca506257b41c32ccc/test/e2e-tests-withdraw.sh#L1-L16

This implies that switching the last two lines in travis script would result in a failed test.

https://github.com/gnosis/dex-services/blob/b43e7dae6c48e4f3c9df115ca506257b41c32ccc/.travis.yml#L38-L41

## Question

Should we be concerned that these tests aren't standalone?

**Comment by fleupold** [comment]
Good find!

The point is that we need to have a deposit in the system before we can make any withdraw. I agree the implicit dependency is not great. The two options I saw were:

1) Make the tests depend on each other (the way it is now)
2) Run multiple (potentially largely overlapping ) tests each in a clean docker environment

One nice thing about using docker, is that we could just run `docker-compose down && docker-compose up` and would have a clean empty blockchain and db state.

I'd suggest for now we combine the two scripts to a single script and collect our main interaction tests (deposit followed by a trade, followed by a withdraw) in that one file (so at least the interdependence is explicit). 

Since it's an e2e and not a unit test, I think it's ok to test a large scenario that assumes certain dependencies.

If we find completely orthogonal scenarios that we would like to test, we can consider making use of restarting the docker landscape between tests.

**Comment by bh2smith** [comment]
Sounds good to me! I will, eventually, take action on this task (probably when doing e2e-auctions)

**Comment by bh2smith** [comment]
My proposed implementation for this is to include both of Deposit & Withdraw into a single end-to-end test.
