### ISSUE TITLE
[event based orderbook] Correct approach for partial solutions

### ISSUE THREAD

**Issue by e00E** [gnosis/dex-services#758]
This is needed when we want to start solving optimistically.

Maybe the correct approach is to not include proceeds if a solution is pratially applied instead of erroring?

_Originally posted by @nlordell in https://github.com/gnosis/dex-services/pull/755_

https://github.com/gnosis/dex-services/pull/903/files#r429848905

**Comment by nlordell** [comment]
I think this is no longer an issue. Since we now use `eth_getLogs` to retrieve events, solutions emit all events in a single block, and we apply all events atomically, I don't think we will ever be in a situation where a solution will be partially applied.

I think the TODO just needs to be cleaned up, and maybe assert that we are never in a partially applied solution at the end of applying events.
