### ISSUE TITLE
Should we only run the deploy CI step on master and omit the tests

### ISSUE THREAD

**Issue by e00E** [gnosis/dex-services#801]
We already run the tests in the state that master would be in in the PRs so running them again adds no useful information. The only step we need for master is running the deploy script.
This would speed up the time it takes to got from PR to deployed docker image significantly.
I don't know if this is possible with travis (probably is), just had this idea while waiting for my hot fix to be deployed.

**Comment by nlordell** [comment]
> We already run the tests in the state that master would be in in the PRs so running them again adds no useful information

This is not strictly true since we currently allow PRs that trivially merge into master even if the branch is not up to date with master which means that the travis tests aren't necessarily performed with the code exactly as it will be on master. If we enable the "Require branches to be up to date before merging" setting (like we have in `ethcontract`) then your statement will be true.

In general I am OK with removing redundant tests but we should be careful that they are indeed redundant.

**Comment by fleupold** [comment]
Let's try it out by requiring PRs being up to date with master before merging. We can also look into bors (a bot which should help preventing merge skews)

If we see it becoming too annoying we can move back to the current scheme.

**Comment by e00E** [comment]
I have enabled this option
![image](https://user-images.githubusercontent.com/1462179/81684275-1c889480-9457-11ea-9ac2-25111d2c5463.png)

**Comment by e00E** [comment]
If someone is familiar with travis it would nice to also do the change that we only deploy on master but not run the tests again.
