### ISSUE TITLE
Solution from previous batch clog solutions for next batch

### ISSUE THREAD

**Issue by e00E** [gnosis/dex-services#821]
> ERROR (pod: dev-dfusion-standard-solver-mainnet-master-68bcc79797-2g5r8):
Apr 30 10:05:56.824 ERRO [driver::driver::scheduler::system] Batch 5294136 failed with unretryable error: method 'submitSolution(uint32,uint256,address[],uint16[],uint128[],uint128[],uint16[]):(uint256)' failure: web3 error: RPC error: Error { code: ServerError(-32010), message: "Transaction gas price supplied is too low. There is another transaction with same nonce in the queue. Try increasing the gas price or incrementing the nonce.", data: None }

I am not (yet) sure what this means. I suspect it could be related to the gas price increases we recently implemented.

**Comment by fleupold** [comment]
Here are the relevant logs: https://logs.gnosisdev.com/goto/7180d991e41316415843e7687ea581bd

### 10:00 UTC Batch 5294135
- Found a solution and submitted with 30GWEI with [nonce 1168](https://www.ethereumdecoder.com/?search=0xf904cc8204908506fc23ac018353ec60946f400810b62df8e13fded51be75ff5393eaa841f80b904642e4c83bd000000000000000000000000000000000000000000000000000000000050c8380000000000000000000000000000000000acfa60cf09f6ab1734b7a4da133b8a00000000000000000000000000000000000000000000000000000000000000e000000000000000000000000000000000000000000000000000000000000001a00000000000000000000000000000000000000000000000000000000000000260000000000000000000000000000000000000000000000000000000000000032000000000000000000000000000000000000000000000000000000000000003c00000000000000000000000000000000000000000000000000000000000000005000000000000000000000000b210d9afde9cda1b8af0d260ad8602f5134f6cac000000000000000000000000e0a0d0081ba638e2c95eb34f2bc949e70ea12ecb000000000000000000000000b210d9afde9cda1b8af0d260ad8602f5134f6cac000000000000000000000000a5a69107816c5e3dfa5561e6b621dfe6294f6e5b000000000000000000000000ec017db25fe89b55e32228240f04b26a332bf3150000000000000000000000000000000000000000000000000000000000000005000000000000000000000000000000000000000000000000000000000000017b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000016700000000000000000000000000000000000000000000000000000000000000250000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000500000000000000000000000000000000000000000000000c2040808bd2c08c6200000000000000000000000000000000000000000000000000079afdea6b1069000000000000000000000000000000000000000000000000000000000006ed93000000000000000000000000000000000000000000000000000000000006efcc0000000000000000000000000000000000000000000000000ed503edbf0836d8000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000f48cc9caa50a981060000000000000000000000000000000000000010c64c875562db034c0eb4d2ac0000000000000000000000000000000000000010cffacf6ccb46fbf1436e735c00000000000000000000000000000000000000000000000012b6cb2edaa9cebd0000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000726a075117ca9df180abff1aaf5700763425763e9061b6eff021ff34989c2e90ec04d9f5a3bb05a933dd20c41cc0aaaa0155259d87e433d1bb0e5fc3f2d1a97713c6a) (I extracted the eth_sendRawTransaction payload from the logs)
- Lost filter to track submission (thus no gas price doubling)
### 10:05 Batch 5294136
- Found a solution and tried submitting with 30GWEI with same [nonce 1168](https://www.ethereumdecoder.com/?search=0xf9070d8204908506fc23ac018353ec60946f400810b62df8e13fded51be75ff5393eaa841f80b906a42e4c83bd000000000000000000000000000000000000000000000000000000000050c83700000000000000000000000000000000140feea81607834d95254f47fe9ba79e00000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000000000000000000000000000000000000000026000000000000000000000000000000000000000000000000000000000000003e000000000000000000000000000000000000000000000000000000000000005600000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000000b0000000000000000000000004b5ec86d420c65dfa802e922513ad7ca5f912486000000000000000000000000010afb8548a5d1a3a3d62f58ca0a5a1329974206000000000000000000000000eb13c6ff42f1307c026a7f6e2c97068658d9aea600000000000000000000000058c88f6a8a61e982701088992e39e0b062ba2608000000000000000000000000b210d9afde9cda1b8af0d260ad8602f5134f6cac000000000000000000000000ae5fb390e5c4fa1962e39e98dbfb0ed8055ed7a900000000000000000000000095d368183934bdfccb2d0068f37afed3d350770a0000000000000000000000002107cb769a932a8cc4e9efa6da6eedea8ed916b8000000000000000000000000a5a69107816c5e3dfa5561e6b621dfe6294f6e5b000000000000000000000000ec017db25fe89b55e32228240f04b26a332bf315000000000000000000000000d47c47aca9ea4d7f4c9c7e629a35b8a61815b1d0000000000000000000000000000000000000000000000000000000000000000b000000000000000000000000000000000000000000000000000000000000001f00000000000000000000000000000000000000000000000000000000000000190000000000000000000000000000000000000000000000000000000000003dbf000000000000000000000000000000000000000000000000000000000000001f000000000000000000000000000000000000000000000000000000000000016700000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002b000000000000000000000000000000000000000000000000000000000000002500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000b000000000000000000000000000000000000000000000000000000001c0854ad00000000000000000000000000000000000000000000000000000000000f88050000000000000000000000000000000000000000000000000000000078bb30e20000000000000000000000000000000000000000000000000000000005a2f2a800000000000000000000000000000000000000000000000000000000005ce8430000000000000000000000000000000000000000000000000000000003985b7800000000000000000000000000000000000000000000002d765a4d09b55aab18000000000000000000000000000000000000000000000000000000000fac049a0000000000000000000000000000000000000000000000000000000011a54e5c00000000000000000000000000000000000000000000000037712ff1390b8f7e0000000000000000000000000000000000000000000000004d65d57c83879595000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000f4b937f23ef6c85d10000000000000000000000000000000000000010c64cde4f7fbe06e39c9809b70000000000000000000000000000000000000010cffad1c41640b27e03d5ddd900000000000000000000000000000000000000000000000012abe5d1b29000050000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000726a0aefffd1170fc2e5c81ebf81d8536a9a8fa361eef7028339f4bf90cc8d9dd74b2a010a8c98209d812191ba3601a8f2dbe7a12db737a78aecae28d7facac0ce849e7) (not the different r, s value)
- Error since same nonce was still pending with same gas price

### 10:06:56
- Original TX for 5294135 failed because no longer accepting solutions
https://etherscan.io/tx/0x6f6423f805f13960154e0457d3c6bda610616ed27c7a21e1d6f58df85973565a

**Comment by fleupold** [comment]
It could be nice, if we can check potentially pending txs from the solver before submitting and make sure if there is one we submit with a marginally higher gas price (which will override the previous tx).

This seems to require keeping the last nonce & gas price around inside the service for the next solving loop to access (I wasn't able to access txs from the mem-pool in a widely accessible way).

**Comment by bh2smith** [comment]
> I am not (yet) sure what this means. I suspect it could be related to the gas price increases we recently implemented.

The ethereum network has been completely clogged all day. I have sent out transactions with gas prices of over 25 that take up to 10 minutes to be mined.

**Comment by fleupold** [comment]
Could potentially be fixed with cancelling solutions after the 4 minute mark (cf. #825)
