### ISSUE TITLE
Make more things async

### ISSUE THREAD

**Issue by e00E** [gnosis/dex-services#843]
Currently we have some mix of blocking code and code that returns futures. It would be cleaner if everything was async (returned futures).

Changing this is somewhat annoying because Rust does not yet support async in traits so all the functions have to return `BoxFuture`.

**Comment by nlordell** [comment]
I'd be up to making this change in `ethcontract` as well.

**Comment by e00E** [comment]
What is left related to this:
Make the top level async: main.rs and the schedulers.
For this we'll want an executor probably tokio or asyncstd to use their task abstraction. I prefer async-std.
When we have that we can change threaded price source to use a Task instead of a background thread.

**Comment by nlordell** [comment]
>  I prefer async-std.

Just curious about your reasons for this (not that I disagree).

**Comment by e00E** [comment]
The main reason is that when I tested tokio and async-std, async-std futures were able to run in all executors (async-std, futures::executor::block_on, tokio) but tokio futures only ran in tokio (panic otherwise).
I can't formulate it exactly but reading docs, blogs, github issues made me like async-std.

**Comment by nlordell** [comment]
> but tokio futures only ran in tokio

Yes, I think it's because tokio futures need to be driven by a tokio reactor (which gets started by the tokio executor).

Ultimately, `async-std` is more about providing an out-of-the box async version of the `std` library which is think is more what we need for this project. I imagine that the price estimator might benefit from tokio for the HTTP service.
