### ISSUE TITLE
Implement service that exposes price estimation functionality

### ISSUE THREAD

**Issue by fleupold** [gnosis/dex-services#948]
We basically want to move https://github.com/gnosis/dex-price-estimator to native rust. We should discuss if the code should live in this repo or get its own.

**Comment by e00E** [comment]
This is related to the pricegraph. Could someone reiterate the arguments for including it in the main repository?

I prefer having price-estimator-rust in it's own repository because it's an individual binary that is code wise unrelated to the driver. Pricegraph could be it's own repository too if is going to be used by both price-esimator-rust and dex-services (to calculate prices for the solver). We don't have to publish it to crates io either, it could be be a git dependency.
I prefer this because it keeps the git repository and history of separate projects separate.

**Comment by e00E** [comment]
Discussed in meeting. Will keep in monorepo for now based on experience with dex-contracts.

**Comment by e00E** [comment]
@gnosis/dex-services 

We need to decide how to reuse the event based orderbook in the new rust price estimator. Ideas:

1. Add the price estimator as another binary target to driver.
2. Add a library target to driver which exports all modules.
3. Add a library crate to the workspace into which the event based orderbook moves.

1 is little work but not clean because the two binaries do very different things. I don't like this long term.
2 is little work and cleaner than 1 because the binaries are separated. It would be cleaner to not export everything in the library when we only need the event based orderbook but that is more work.
3 is more work but the cleanest approach. It involves disentangling other driver dependencies of the event based orderbook like the StableXOrderBookReadingTrait.

I like 2 the most because it is practical right now. For 3 it is unclear how much benefit we would get out of this. We could do 3 later if we want to make another separate binary that also uses the event based orderbook.

**Comment by nlordell** [comment]
We can also do a 2/3 hybrid where we create a new `gnop-core` that is exactly the `driver` `lib` target from #951 and then have a `driver` binary and `price-estimator`as separate crates.

**Comment by e00E** [comment]
I like your suggestion the most. Changed the PR to that.

**Comment by nlordell** [comment]
I had some thoughts about how we can structure the price estimator service for **MAXIMUM THROUGHPUT** :racehorse: :car: :rocket:

We could have `n = num_cpu` fibers, each with their own price estimator component (which owns the `pricegraph::Orderbook` for estimating prices).

The HTTP service would send a message to a bounded shared channel requesting a price estimation or transitive orderbook, along with a one shot channel for the result. The fibers would then take the request, process it, and then send the response back:

```rust
enum Request {
    PriceEstimate {
        pair: TokenPair,
        amount: f64,
        response: oneshot::Sender<f64>
    },
    Orderbook {
        pair: TokenPair,
        response: oneshot::Sender<TransitiveOrderbook>
    },
}
```

- The bounded channel would give us a cap on maximum number of concurrent requests, so the service would correctly handle having too many requests when it becomes too backed up.
- The response channel makes the requests be type-safe :smile: 
- multiple fibers with correctly configured Tokio would allow us to really use all available CPUs (since I suspect that will be the limiting factor for the service).

We would also need a broadcast channel to send orderbook updates to each of the workers.

I think this would give us super speedy service :smile:

**Comment by nlordell** [comment]
I also believe that since this is a user-facing service, it is worth investing some time (and some code complexity) to make sure it runs as fast as possible. Low latency responses here are, IMO, important for user satisfaction.

**Comment by e00E** [comment]
Thanks for sharing your thoughts. I am not sure how the final architecture will be yet. I am going to start with a simple implementation. I had in mind that we have one pricegraph::Orderbook that is cloned for each request. I expect the clone to be a lot faster than the price estimation and the response overall to be a lot faster than the nodejs version.
Once we have this running we can try other approaches to avoid the clone like what you describe.

**Comment by nlordell** [comment]
> We need to clone anyway because estimating a price modifies the orderbook.

:+1: 

> Once we have this running we can try other approaches to avoid the clone like what you describe.

I totally agree - this is more of an architecture to make maximum use of all CPUs. (Although we can probably iterate on this more).

I wouldn't be surprised if existing HTTP frameworks might do this kind of thing for you under the hood.

**Comment by fleupold** [comment]
@e00E can this task be closed?
